# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'Fonting Awesome' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Fonting Awesome
	pod 'FontAwesomeKit', '~> 2.2.0'
	pod 'CWStatusBarNotification', '~> 2.3.4'

end
